### ISSUE TITLE
[1.21] NeoForge crash on server startup

### ISSUE THREAD

**Issue by NielsPilgaard** [Mysticpasta1/Dimension-Atlantis#107]
Hi 👋 

Atlantis crashes on servers at the moment.

- atlantis-2024.7.10-1.21-1.0.0-neoforge

https://gist.github.com/NielsPilgaard/b0cb280a7f1a10e8651ae9d069bb9b62

**Comment by Mysticpasta1** [comment]
try newest version for 1.21 see if it crashes

**Comment by NielsPilgaard** [comment]
Now it crashes due to the mod JustHammers being missing, I guess that's a hard dependency?
https://gist.github.com/NielsPilgaard/81a0a7e31c04b8530ee3b453b024beb7

D'oh, and it's missing because I only copied Atlantis from my client to the server. 
Yes it's working 😂 

I don't understand the hard dependency on a hammer mod though tbf
