### ISSUE TITLE
I can not mine Aquamarine.

### ISSUE THREAD

**Issue by Joe-327** [Mysticpasta1/Dimension-Atlantis#109]
I have tried to mine with diamonds and a aquamarine pixaxe nothing works.

**Comment by XCORNN** [comment]
same here, it seems you can't pick with any kind of pick.

**Comment by Mysticpasta1** [comment]
what version of minecraft

**Comment by meesso** [comment]
im on 1.20.1 and have the same problem, also ancient metal doesnt drop as raw ore but as the block and theres no recipe to convert it.

**Comment by Mysticpasta1** [comment]
fixed in newest version for 1.20.1 forge
