### ISSUE TITLE
Neoforge 1.21 - Boat mixin crashes the game

### ISSUE THREAD

**Issue by Saereth** [Mysticpasta1/Dimension-Atlantis#110]
Attempting to place a boat causes the boat to sink, not float on water and then trying to get into it causes the game to crash. 

Neoforge 21.0.160
MC 1.21

Crashlog: https://mclo.gs/k02jnRf

relevant bit:
```
Description: Ticking entity
 java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.vehicle.Boat$Status.ordinal()" because the return value of "net.minecraft.world.entity.vehicle.Boat.getStatus()" is null
```

Let me know if I can provide any more information or testing, thanks!

**Comment by Mysticpasta1** [comment]
ok I will have to fix this later next week
