### ISSUE TITLE
embeddium batching crash with atlantis when going to the surface in 1.19.2 forge

### ISSUE THREAD

**Issue by loti1234** [Mysticpasta1/Dimension-Atlantis#111]
https://mclo.gs/EdWXWWi

for extra context i had also oculus active with the shader yofps shader (chocapic13 edit)
also yes ik that its most certanly likely an embeddium issue but they dont support 1.19.2 rn i think so im posting it here to see if there could be a workaround this crash

**Comment by Mysticpasta1** [comment]
I might look into it but I don't typically support 1.19.2 anymore

**Comment by loti1234** [comment]
btw i tested it more and it might be also something to do with shaders changing the atlantis sun to a diffrent sun

**Comment by Mysticpasta1** [comment]
I don't have time to fix it, going to close the issue for now I might come back to it later
