### ISSUE TITLE
broken portals

### ISSUE THREAD

**Issue by btd6player27** [Mysticpasta1/Dimension-Atlantis#112]
portals do not work in my modpack, here is crash log. mod loads in fine, but as soon as i try to go through a portal into atlantis, game crashes
[crash-2024-11-19_18.25.13-server.txt](https://github.com/user-attachments/files/17823759/crash-2024-11-19_18.25.13-server.txt)

**Comment by Mysticpasta1** [comment]
need a version of minecraft and atlantis
