### ISSUE TITLE
Music discs won't play in jukebox

### ISSUE THREAD

**Issue by son0fether** [Mysticpasta1/Dimension-Atlantis#113]
Minecraft 1.20.1
Atlantis 6.2
Forge 47.3.12

I can't put the music discs "LudoCrypt - panbee" or "Firel - column cavitation" into the vanilla Minecraft jukebox.  Other modded music discs work, such as from Blue Skies.  The music discs do work in the jukebox upgrade from Sophisticated Backpacks, and play just fine in those.

**Comment by Mysticpasta1** [comment]
will be fixed in the next version
