### ISSUE TITLE
Atlantean Spear has negative speed (-1.2)

### ISSUE THREAD

**Issue by son0fether** [Mysticpasta1/Dimension-Atlantis#114]
Minecraft 1.20.1
Atlantis 6.2
Forge 47.3.12

The Atlantean Spear has attack damage of 10, which is normal, and a speed of -1.2, which is not.  That's a negative speed, so it never refills the 'ready bar'.  It was probably meant to be 1.2.  That would make it slightly better than a netherite axe (damage 10, speed 1.0).

**Comment by Mysticpasta1** [comment]
fixed in dev
