### ISSUE TITLE
1.17 1.7.0 Orb of Atlantis Doesn't Work

### ISSUE THREAD

**Issue by VaelophisNyx** [Mysticpasta1/Dimension-Atlantis#25]
as the title says, the orb fails to do anything. Additionally killing a guardian doesn't drop a portal?

**Comment by Mysticpasta1** [comment]
read the description of the mod page pls
![image](https://user-images.githubusercontent.com/45608372/123541605-fe3d3100-d70a-11eb-843d-b85b18de7c13.png)
after 1.5.0-1.17 the orb is disabled for something new later on and the LEGACY portal of Atlantis is creative only! Due to it being to deadly in survival. :D

**Comment by VaelophisNyx** [comment]
Yeah I did read that. It's worded incredibly confusingly.

*how* do you get to Atlantis in the current version of the mod

**Comment by Mysticpasta1** [comment]
you need the block called Atlantean Core and a bucket of water, build the Atlantean Core blocks like obsidian to a nether portal, and activate it with the bucket of water by right clicking.

**Comment by Mysticpasta1** [comment]
this assumes you know how to build a nether portal in the first place

**Comment by Mysticpasta1** [comment]
if you are still having trouble look to the images tab

**Comment by VaelophisNyx** [comment]
well, i've done this
the portal itself doesn't work. It never takes you there.

**Comment by Mysticpasta1** [comment]
can you show me on discord my name is Hauntedpasta1#8200 on there

**Comment by whatebbs** [comment]
I have 1.20.1 and followed the updated method, and I still can't get it to work either.

**Comment by Mysticpasta1** [comment]
read the mod page pls if you have a question about it post it on discord no in a closed issue
