### ISSUE TITLE
Water Breathing potion effect doesn't work

### ISSUE THREAD

**Issue by Maccysundae** [Mysticpasta1/Dimension-Atlantis#26]
I have found an issue where using this modpack: [https://www.curseforge.com/minecraft/modpacks/noonmc-origins-modpack](url) the water breathing effect doesn't work. I did manage to narrow the mod causing the issue to Atlantis. I am unsure of whether this is a compatibility issue with origins or one of the other mods within the modpack.

**Comment by piemanau** [comment]
Can you provide us with a log?

**Comment by Maccysundae** [comment]
[latest.log](https://github.com/Exploding-Creeper/atlantis/files/6784352/latest.log)

**Comment by Mysticpasta1** [comment]
not sure what is happening either I will do more testing with origins in the future to see if there is an issue with the water breathing effect, for now don't use it in Atlantis :D
