### ISSUE TITLE
Atlantis breaks waterbreathing and respiration enchants.

### ISSUE THREAD

**Issue by Frost-wood** [Mysticpasta1/Dimension-Atlantis#30]
With Atlantis installed, you can drown even with waterbreathing potion effects, and respiration doesn't seem to work as well.

Disabling the mod fixes the issue.

**Comment by Mysticpasta1** [comment]
what version of the mod and what game version

**Comment by Mysticpasta1** [comment]
if this is 1.16.5, 1.17 fixes the issue if not and it is 1.17 still DM me on discord at Hauntedpasta1#8200

**Comment by Frost-wood** [comment]
It's 1.17
