### ISSUE TITLE
Specific effects not working

### ISSUE THREAD

**Issue by Xavbeat03** [Mysticpasta1/Dimension-Atlantis#31]
The effects Haste and Water breathing aren't working when I have this mod enabled. I cannot seem to activate them through any method including custom potions and commands. Sometimes the effect will appear for a split second and then disappear.

**Comment by Mysticpasta1** [comment]
what version of the mod and what game version

**Comment by Xavbeat03** [comment]
I am using 1.16.5 with the appropriate version of the mod

**Comment by Mysticpasta1** [comment]
try the 1.17 version it should fix the problem :D
