### ISSUE TITLE
Multiple issues with licenses

### ISSUE THREAD

**Issue by triphora** [Mysticpasta1/Dimension-Atlantis#33]
Hi,

The `License Readme.txt` file lists the LGPL-3.0 as the code license, and that is also the license listed on the Modrinth and Curse pages... however, the file `LICENSE for Code` has the GPL-3.0, which is invalid for Minecraft mods (the LGPL-3.0 is not invalid). It is important to keep in mind that the LGPL-3.0 is not the same as the GPL-3.0, and the "GLPL v3" mentioned on the Modrinth and Curse pages does not exist. Please correct the file `LICENSE for Code` to have the LGPL-3.0, and the Modrinth and Curse pages to have "LGPL v3" (or something similar) in the description, not the "GLPL v3".

Additionally, it is mentioned in `License Readme.txt` that `LICENSE for Art` should be only "All Right Reserved", but the BSD-2-Clause is not the same as All Rights Reserved. Please correct the file `License Readme.txt` to list the "textures or models" license as BSD-2-Clause.

Finally, the `License Readme.txt` file says that the `LICENSE for Noise` applies to the file `FastNoiseLite.class`. No such file exists, but if you mean `FastNoiseLite.java`, you are claiming that the "Exploding Creeper Group" is the copyright holder of this file under the MIT license in 2021. However, this is not true; `Jordan Peck (jordan.me2@gmail.com)` & `Contributors` are the copyright holders under the MIT license in 2020. Please correct the file "LICENSE for Noise" to have the correct copyright holders as mentioned at the top of `FastNoiseLite.java`.

Thank you.

**Comment by Mysticpasta1** [comment]
https://github.com/Exploding-Creeper/atlantis/commit/ae48747e2cf93d5992ec0d0530cccf1f5e1a4705
https://github.com/Exploding-Creeper/atlantis/commit/29e38cce5d1500bd574f26257863f39a6f4be7d8
https://github.com/Exploding-Creeper/atlantis/commit/0d1f20261af5e065256a68abb777d7e8ed51376a
https://github.com/Exploding-Creeper/atlantis/commit/8c9c347ef10436b7324a312413d6950b6360d792

I fixed the licenses based off of your issue :D thank you for reporting it.

**Comment by triphora** [comment]
Awesome, thank you!
