### ISSUE TITLE
atlantis don't work in 1.17.1 in my case

### ISSUE THREAD

**Issue by perikitodestino** [Mysticpasta1/Dimension-Atlantis#39]
Hi! I am unable to get this mod to work, I provide two logs. The first one is with a variety of mods and the second one is only with the essentials in a clean install... In no case does it start.

More mods: https://paste.ee/p/v9Txk
Clean install (with Fabric API and GeckoLib): https://paste.ee/p/2SKIZ

I just can't get it to work... What am I doing wrong?, thanks.

**Comment by hypherionmc** [comment]
Seems you are missing Cloth Config. The author should mention this somewhere

**Comment by perikitodestino** [comment]
> Seems you are missing Cloth Config. The author should mention this somewhere

In the instance with many mods it was. I re-created a new instance with Fabric API, GeckoLib, Cloth Config and Atlantis only (to rule out incompatibilities) and.... "cata crash: https://paste.ee/p/FBU5C

ty for the response!

**Comment by hypherionmc** [comment]
In that crash it says you are missing geckolib.

`[15:36:34] [ForkJoinPool-1-worker-27/WARN]: Non-Fabric mod JAR at "D:\Minecraft\instances\Atlantis\.minecraft\mods\geckolib-1.17.1-3.0.2.jar", ignoring`

You might have the forge version instead of the fabric version

**Comment by perikitodestino** [comment]
> In that crash it says you are missing geckolib.
> 
> `[15:36:34] [ForkJoinPool-1-worker-27/WARN]: Non-Fabric mod JAR at "D:\Minecraft\instances\Atlantis\.minecraft\mods\geckolib-1.17.1-3.0.2.jar", ignoring`
> 
> You might have the forge version instead of the fabric version

Upsssss... I can't find GeckoLib version for fabric and mc 1.17... :S

But yes, that was the error... Thank you very much!

**Comment by perikitodestino** [comment]
Ok, found this... but bad log: https://paste.ee/p/M8kRw

XD

**Comment by Mysticpasta1** [comment]
try running again with the newest version of 1.17.1
