### ISSUE TITLE
[1.16 Forge] No config options for oregen, and also ignores Ore Tweaker configs.

### ISSUE THREAD

**Issue by Neamow** [Mysticpasta1/Dimension-Atlantis#42]
Hi team,

I was looking at integrating the mod into a dimension-oriented modpack, but noticed it has no configs at all.

One thing I'd like to tweak is oregen, namely:
1. turn off Aquamarine ore generation in the Overworld
2. turn off vanilla ore generation in Atlantis

Since Atlantis doesn't have any configs, I tried setting it through Ore Tweaker, but was only half successful.

1. Creating a JSON for aquamarine ore and putting the atlantis biome into the whitelist successfully stopped generating it in any other dimension than Atlantis itself.
2. Editing the vanilla ores (e.g. iron, coal, gold...) JSONs by adding the atlantis biome in blacklist had no effect - the ores still generate in Atlantis.

Is there a way to fix the oregen, expose it to be editable by Ore Tweaker, or create a config for Atlantis that has these options?

Thanks!

**Comment by Mysticpasta1** [comment]
I might look into this in the future but for now our focus is fabric atm
