### ISSUE TITLE
armor bar disappear

### ISSUE THREAD

**Issue by BrokenDawn627** [Mysticpasta1/Dimension-Atlantis#50]
this mod make my armor bar disappear in my modpack Infinity. version is 1.18.1
https://www.curseforge.com/minecraft/modpacks/infinity-fabric

**Comment by Mysticpasta1** [comment]
hello, yes this has been confirmed in another modpack. I'm checking to see if it is another mod causing it as Atlantis doesn't touch the armor bar code yet.

**Comment by Mysticpasta1** [comment]
it is another mod causing it atm I will look for want the mod is but for now this issue will be closed :D
