### ISSUE TITLE
Crash when spawning Sub

### ISSUE THREAD

**Issue by Gamerbolts** [Mysticpasta1/Dimension-Atlantis#51]
Hello! I am creating a modpack and put your mod in it and when I was testing I spawned the Sub and my client crashed to desktop. The server is still up and fine however. Here is the crash log and latest. Any help is appreciated! Thank you.

[crash-2022-02-07_17.47.13-client.txt](https://github.com/Exploding-Creeper/atlantis/files/8019493/crash-2022-02-07_17.47.13-client.txt)
[latest.log](https://github.com/Exploding-Creeper/atlantis/files/8019494/latest.log)

**Comment by Mysticpasta1** [comment]
yes I fixed the problem but I never but it up on CF I will try to get it up tonight along with some other feature if not then it will be tomorrow
:D

**Comment by Gamerbolts** [comment]
Awesome! Thanks so much!
