### ISSUE TITLE
Redstone power level decreased by 1

### ISSUE THREAD

**Issue by theo-matzavinos** [Mysticpasta1/Dimension-Atlantis#53]
Put redstone dust next to a redstone block. The redstone dust has 14 power instead of 15.

**Comment by Mysticpasta1** [comment]
this has been confirmed :D, trying to fix it.

**Comment by Mysticpasta1** [comment]
the redstone block has a level of 15 therefore in this mod the level goes down by 1 when it goes into the redstone dust making it 14, it should be fine if you place a repeater with no tick delay or by moving it closer to the contraption, will be looked at in the future but atm no plans on fixing it.
