### ISSUE TITLE
[request] Config option

### ISSUE THREAD

**Issue by KMFrench1** [Mysticpasta1/Dimension-Atlantis#54]
Can you add a config option to turn off the the permanent water breathing, haste and night vision. In my mod pack I have other ways to get those and I want people to use them when traveling to Atlantis. I don't want it to be free.
Thanks

**Comment by Mysticpasta1** [comment]
we can do that for the next update of 1.18.1 forge

**Comment by Mysticpasta1** [comment]
forge
