### ISSUE TITLE
1.18.2 has a mixin error

### ISSUE THREAD

**Issue by Sunconure11** [Mysticpasta1/Dimension-Atlantis#62]
https://pastebin.com/7uU1avQW

When the time comes to port this, 1.18.2 has a mixin error with this mod currently.

**Comment by recon88** [comment]
mixin error still not fixed (most likely because not updated to 1.18.2)
1.1.1 with 0.14.5 fabric loader
https://pastebin.com/raw/Ceah1aqF

**Comment by Mysticpasta1** [comment]
the mod is 1.18.1 not 1.18.2, and we have moved to forge not fabric for now that way we can abuse forge events and mixins :D

**Comment by recon88** [comment]
Sad to hear. Still looking forward for an Fabric update.
