### ISSUE TITLE
No Armor bar showing when installed with Detail Armor Bar

### ISSUE THREAD

**Issue by Gamerbolts** [Mysticpasta1/Dimension-Atlantis#63]
Hello! I have your mod on my modpack Bolt's Crazzy Adventure. I noticed my armor bar had disappeared and went and checked all my mods, it is between your mod and Detail Armor Bar (https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar). I even tried with only detail armor bar and cloth config/geckolib and the armor bar showed up then, it is only when I add Atlantis that the armor bar disappears. I am not sure if a log will be helpful for you but here it is.
[2022-04-15-1.log](https://github.com/Exploding-Creeper/atlantis/files/8508435/2022-04-15-1.log)
 
I also posted on the github of Detail Armor Bar mod, but no response from them. Any help is appreciated. Thanks!

**Comment by Mysticpasta1** [comment]
remove detailed armor bar temporarily as I have no idea why the armor bar does this between the two mods
