### ISSUE TITLE
Problem with version 1.18.1 in Fabric 0.14.4

### ISSUE THREAD

**Issue by ERHOR** [Mysticpasta1/Dimension-Atlantis#64]
Install the mod in Aternos for version 1.18.1 using Fabric 0.14.4. But I can't enter the dimension. 

When I try to go through the portal, it doesn't load the dimension (Atlantis).

Also, if I mixed the Aquamarine armor with a skeleton head, it crashes the account.

**Comment by Mysticpasta1** [comment]
I don't support aternos, pls use bisecthosting with code MYSTICAL, and we have move to forge to abuse the forge events with mixins
