### ISSUE TITLE
assorted issues with 1.19.2

### ISSUE THREAD

**Issue by Zygus42** [Mysticpasta1/Dimension-Atlantis#67]
(1) Aquamarine ore does not recognize any picks as valid for mining the block, and thus does not drop anything- tried Iron, Diamond, Netherite & Orichalcium.

(2) Orb of Atlantis does not do anything on right-click.

(3) Portal to Atlantis does not activate - see attached picture: 

![2022-09-22_13 39 44](https://user-images.githubusercontent.com/20757445/191667703-db395d2e-ba44-48c0-9dde-9729c185d8de.png)

 - also tried building one underwater as shown in your picture - also failed to activate.

To double-check that it wasn't a mod-conflict, I tried a run with just your required mods, and same results.
   atlantis-2022.9.4-1.19.2-1.0.3-forge
   cloth-config-8.2.88-forge
   customportalapi-0.0.1-beta50-1.19.2
   geckolib-forge-1.19-3.1.21

   forge-1.19.2-43.1.25-installer

See attached log:
[latest.log](https://github.com/Exploding-Creeper/atlantis/files/9622639/latest.log)

**Comment by Mysticpasta1** [comment]
issue 1) I will look into it, it maybe that I forgot a loot table

issue 2) is a feature it is used in crafting recipes

issue 3) isn't build properly build it flat to the ground! look at the pictures on the mod page in the images tab for more info. Also must be activated by water place by water bucket on the inside of the portal on one of the sides

**Comment by Mysticpasta1** [comment]
should be fixed in 1.3.1 for 1.19.2
