### ISSUE TITLE
Confliction with Create mod

### ISSUE THREAD

**Issue by KnightSpartan** [Mysticpasta1/Dimension-Atlantis#68]
When paired with the Create mod a crash occurs when a block from Create is placed.
[crash-2022-10-06_13.18.59-client.txt](https://github.com/Exploding-Creeper/atlantis/files/9728518/crash-2022-10-06_13.18.59-client.txt)
Create adds some cool things like diving gear which is perfect for exploring Atlantis so I wanted to pair them together but I'm having trouble.

**Comment by Mysticpasta1** [comment]
Please test only with Atlantis and Create for more help, this is in a modpack and we can't determine cause of crash.

**Comment by ArcaneSan** [comment]
Crash when pondering create block when having Atlantis installed
Forge 43.2.0
Atlantis 2022.12.22-1.19.2-1.2.2
Create 0.5g

[crash-2022-12-26_11.46.52-client.txt](https://github.com/DimensionalDevelopment/atlantis/files/10304160/crash-2022-12-26_11.46.52-client.txt)


Hoping onto this as I was having issues with it as well alongside some issues such as when placing a create block, in this instance, the train tracks

More specifically create's special placement when creating a line of tracks

[crash-2022-12-26_11.51.28-client.txt](https://github.com/DimensionalDevelopment/atlantis/files/10304165/crash-2022-12-26_11.51.28-client.txt)

**Comment by Mysticpasta1** [comment]
This is fix in the next version of atlantis for 1.19.2
