### ISSUE TITLE
Crash renders Jelly Fish, jelly fish2, shrimp and submarine 1.19.2

### ISSUE THREAD

**Issue by senechal2702** [Mysticpasta1/Dimension-Atlantis#70]
I created a modpack that uses your mod "atlantis-2022.11.6-1.19.2-1.1.1", when I enter the dimentions a crash occurs.
Here is the crash reaport: https://pastebin.com/XgNb0PWW
The modPack is "Line Of Horizons" on CurseForge.

**Comment by Mysticpasta1** [comment]
This is fixed in 1.2.0 hotfix :D
