### ISSUE TITLE
algae problems megathread

### ISSUE THREAD

**Issue by Kierancraft** [Mysticpasta1/Dimension-Atlantis#71]
Hi guys post your issues with algae here
1. Game crashes because algae casts to random
2. When algae is placed, it places water which doesn't flow
3. Algae doesn't let light pass through
4. Algae can't be placed on the floor
5. I haven't tested if it is (because my game keeps crashing), but if it isn't compostable, it should be, as algae is known to work as a good fertilizer

**Comment by Mysticpasta1** [comment]
I will look into this algae was always a problematic block

**Comment by Mysticpasta1** [comment]
Will be fixed in 1.3.1 for 1.19.2
