### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Youzeer** [Mysticpasta1/Dimension-Atlantis#75]
Aquamarine mines cannot be mined with pickaxes of any kind, pearl blocks cannot be mined with tools of any kind, and many entities in Atlantis have noticeable delays or failure to respond to damage.
https://youtu.be/mMDhIetOdJw

**Comment by Mysticpasta1** [comment]
I need to know your pc specs and RAM used for the instance

**Comment by Mysticpasta1** [comment]
also if you can use the mod spark and send it's data about the lag that would be great

**Comment by Youzeer** [comment]
![Uploading 257b03826139d843.jpg…]()
![-37585d3dc04cca34](https://user-images.githubusercontent.com/125741121/224875211-d2135925-477e-4f74-92e1-ea4224fd54ba.jpg)
![Uploading 7d1a957b8c5a50f1.jpg…]()


> 另外，如果您可以使用 mod spark 并发送有关滞后的数据，那就太好了

**Comment by Youzeer** [comment]
> 我需要知道您的电脑规格和用于该实例的 RAM

![Uploading 257b03826139d843.jpg…]()

**Comment by Youzeer** [comment]
> also if you can use the mod spark and send it's data about the lag that would be great

![-430b396f0ed49edd](https://user-images.githubusercontent.com/125741121/224876934-89da9a1f-2605-4d3c-a7d8-0d066beb5f7e.jpg)
![9a62a84018b22a5](https://user-images.githubusercontent.com/125741121/224876952-739179d6-1580-4cea-8a3d-4525387b04ff.jpg)
![-7b5b18360414d8d5](https://user-images.githubusercontent.com/125741121/224876969-e49f5430-e67a-4270-8492-448792a71c4f.jpg)

**Comment by Youzeer** [comment]
> 另外，如果您可以使用 mod spark 并发送有关滞后的数据，那就太好了

Latency spikes are caused by 5k or so entities, which are either kelp drops or falling sand

**Comment by Mysticpasta1** [comment]
those are screenshots not the spark mod logs

**Comment by Youzeer** [comment]
> those are screenshots not the spark mod logs

I don't know how to use spark

**Comment by Youzeer** [comment]
> 这些是屏幕截图而不是 spark mod 日志

https://spark.lucko.me/j7Fp3Q0aFo

**Comment by Mysticpasta1** [comment]
> > 另外，如果您可以使用 mod spark 并发送有关滞后的数据，那就太好了
> 
> Latency spikes are caused by 5k or so entities, which are either kelp drops or falling sand
#77 fixed - use 1.7.2 and regenerate the dimension

as for loot tables your waiting on another coder to finish it!

**Comment by Mysticpasta1** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/atlantis/files/4615636 sorry for any delays
