### ISSUE TITLE
Some blocks have no way to break and don't drop

### ISSUE THREAD

**Issue by senechal2702** [Mysticpasta1/Dimension-Atlantis#76]
Some blocks such as (aquamarine ore) do not have a means of breaking with a pickaxe, if it is done with a pickaxe the block or the mineral does not give anything in loots.

Example of another block in the same problem:
Algae block
Nautilus shell Block
Atlantic Planks
Oyster shell Block
etc...

atlantis-2023.1.27-1.19.2-1.4.0-forge

**Comment by Mysticpasta1** [comment]
can you give me a full list of block so I know which ones to fix

**Comment by senechal2702** [comment]
Yes I will send it to you. I noticed that you had sent me a private message on my discord account, but I couldn't answer you because you blocked this option, here is my discord link to connect to it and talk about my modpack 'Line of Horizons".
https://discord.com/invite/fahsm8Fz7v

**Comment by senechal2702** [comment]
yes, breaking and drop.

atlantean:
	button
	fence 
	pressure plate
	log
	wood boat
	power stone
	power lamp
	power lever
	power torch
	power repeater
	power comparator
	power dust
	power tripwire hook

ancient wood moss fence:
	acasia
	oak
	spruce
	jungle
	dark oak
	birch

orichalcum block
bubble magma
hardened calcite block

linguistic:
	glyph
	block

sunken gravel
soduim bomb

yes, breaking and verry verry long time to break.


atlantean_door
ancient_jungle_wood_moss_door
ancient_oak_wood_moss_door
ancient_spruce_wood_moss_door
ancient_acacia_wood_moss_door
ancient_dark_oak_wood_moss_door
ancient_birch_wood_moss_door
dead_glowstone
cracked_glowstone

no dropping and verry verry long time to break.

white_colored_shell_block
red_colored_shell_block
orange_colored_shell_block
magenta_colored_shell_block
pink_colored_shell_block
green_colored_shell_block
yellow_colored_shell_block
purple_colored_shell_block
light_blue_colored_shell_block
light_gray_colored_shell_block
lime_colored_shell_block
blue_colored_shell_block
black_colored_shell_block
brown_colored_shell_block
cyan_colored_shell_block
gray_colored_shell_block
atlantean_stairs
atlantean_trapdoor
atlantean_fence_gate
atlantean_slab
atlantean_planks
chiseled_aquamarine
algae_block
oyster_shell_block
nautilus_shell_block
algae_detritus_stone
aquamarine_ore
chiseled_golden_block
chiseled_golden_aquamarine
detritus_sandstone
sea_salt_chunk
writing_block
block_of_aquamarine
atlantean_core
ocean_lantern
atlantean_sea_lantern
atlantean_prismarine
yellow_underwater_flower
underwater_flower
red_underwater_flower
purple_glowing_mushroom
all colors pearl block
yellow_glowing_mushroom
ancient_birch_wood_moss_slab
ancient_acacia_wood_moss_slab
ancient_oak_wood_moss_slab
ancient_jungle_wood_moss_slab
ancient_spruce_wood_moss_slab
ancient_dark_oak_wood_moss_slab
ancient_dark_oak_wood_moss
ancient_oak_wood_moss
ancient_jungle_wood_moss
ancient_spruce_wood_moss
ancient_birch_wood_moss
ancient_acacia_wood_moss
ancient_dark_oak_wood_moss_trapdoor
ancient_jungle_wood_moss_trapdoor
ancient_oak_wood_moss_trapdoor
ancient_spruce_wood_moss_trapdoor
ancient_birch_wood_moss_trapdoor
ancient_acacia_wood_moss_trapdoor
ancient_oak_wood_moss_stairs
ancient_jungle_wood_moss_stairs
ancient_dark_oak_wood_moss_stairs
ancient_birch_wood_moss_stairs
ancient_spruce_wood_moss_stairs
ancient_acacia_wood_moss_stairs

another bug noticed.

atlantean_sign : this drop when it is on the ground, does not drop when it is on a wall
atlantean_leaf_block : when the leaves are placed on the ground (the solid block ground) a transparency is created.

**Comment by Mysticpasta1** [comment]
remember some of the blocks like pearls are silk touch only and some block require better than iron, try using netherite silk touch on them and see if they drop

**Comment by Youzeer** [comment]
> 记住一些像珍珠这样的方块只有丝绸般的触感，而有些方块需要比铁更好的东西，尝试在它们上使用下界合金丝绸般的触感，看看它们是否掉落



> remember some of the blocks like pearls are silk touch only and some block require better than iron, try using netherite silk touch on them and see if they drop
I have done a test, none of the above blocks can be collected with silk touch

**Comment by senechal2702** [comment]
I just tested the pearls with silk touch it does not work, and when I tested all the cettai blocks with a netherite pickaxe.

**Comment by Mysticpasta1** [comment]
fixed in https://www.curseforge.com/minecraft/mc-mods/atlantis/files/4615636
