### ISSUE TITLE
Incredibly laggy after one minute in Atlantis Dimension -atlantis-2023.3.18-1.19.2-1.6.0-forge.jar Version-

### ISSUE THREAD

**Issue by SkyBytett** [Mysticpasta1/Dimension-Atlantis#77]
So I've tried playing the mod in my personal modpack with Forge (I basically have a folder with mods for my own personal use) and when I entered the Atlantis dimension, things would run smoothly and then get incredibly lagging where I move my mouse and the camera would barely move like the frame rate gets so bad. I tried playing with the mod without any other mods, I've tried allocating more memory to Minecraft, and I've tried changing graphics and fps in the options menu in Minecraft itself and I can't get it to stop being laggy. It usually gets laggy if I swim up (hit the spacebar more than once) or if I approach a structure like a volcano, an island or a castle. I took a pic of a modpack with just only Atlantis (and the mods that automatically get downloaded when you download Atlantis) and a video of me playing in a creative world with that modpack. 

Video Link: https://youtu.be/5tUClZeZP0I

![Atlantis](https://user-images.githubusercontent.com/132015553/234992867-88c47176-0f72-478e-9773-3c58c625a41c.jpeg)

**Comment by RechercheRaptor** [comment]
The same kind of thing happened to me (forge version 43.2.0, Atlantis version 2023.18-1.19.2-1.6.0-forge), except the minute I entered the dimension my fps immediately dropped to one. Also, is dying in Atlantis supposed to spawn you back at the Atlantis portal in the Atlantis dimension?

**Comment by Mysticpasta1** [comment]
lag issues are known it is due to entity spawn rates being fucked, unless your near an atlantean city then that structure can cause huge amounts of lag too, recommend to turn it off for now.

**Comment by RechercheRaptor** [comment]
Turn off the mod or? Like is there anything I can do, or just wait for an update to fix spawn rates?

**Comment by Mysticpasta1** [comment]
try the new version 1.7.2 it fixes the lag with volcanoes, and the cities are off by default for now and should only be turned on for testing reasons

you must re-generate the dimension to see any difference!
