### ISSUE TITLE
Too many Entities are spawning. Causes MAJOR Lag Spikes

### ISSUE THREAD

**Issue by PlatinumFox** [Mysticpasta1/Dimension-Atlantis#79]
Trying this mod out for the first time and so many entities are spawning that the game becomes unplayable. I have a really beefy PC (Specs in photos) and i was at 0 FPS at times. I did not crash the game but it took a very long time to float back to the bottom where there were less mob entities. 

![2023-05-23_17 07 56](https://github.com/DimensionalDevelopment/atlantis/assets/23727270/69d6d455-d4f1-40a4-befe-698d047790c3)
![2023-05-23_17 08 13](https://github.com/DimensionalDevelopment/atlantis/assets/23727270/65df25e6-fd94-498f-8768-1fd025bdf7ca)
![2023-05-23_17 12 36](https://github.com/DimensionalDevelopment/atlantis/assets/23727270/06ff5c94-f34b-4abd-bccc-3924c4ebb0d4)
![2023-05-23_17 12 53](https://github.com/DimensionalDevelopment/atlantis/assets/23727270/fce97356-ea0b-4243-99a0-3cdc7baef00e)

**Comment by Purpledudes** [comment]
omg im having the same issue literally unplayable

**Comment by Zackariex** [comment]
this was the most stressful time of my friend groups life.

**Comment by Mysticpasta1** [comment]
will be fixed in the next update for 1.19.2 forge

**Comment by hokomili** [comment]
still occurs in 1.20.1-1.4.0-forge
![2023-10-19_20 47 47](https://github.com/DimensionalDevelopment/atlantis/assets/28939939/0834e96e-ad5a-49f2-b4e0-10c6f8f64bea)
