### ISSUE TITLE
Major Boot time Crash happens on atlantis version 1.7.4 of mc 1.19.2

### ISSUE THREAD

**Issue by Devilswarchild** [Mysticpasta1/Dimension-Atlantis#80]
been trying to fix an issue with my modpack by testing it after updating the mods one by one and when I updated your mod I got an HS error immediately after mc starts its boot up sequence.

[hs_err_pid19264](https://mclo.gs/070qKUs)

[debug.log](https://mclo.gs/oO8SEOL)

[launcher_log](https://mclo.gs/jHOhKJG)
[
latest.txt](https://mclo.gs/ZLN3UUd)

not sure what all was changed in the latest update but it most definitely broke something.

list of mods im using

mods in my modpack:

[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)

[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)

[Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)

[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)

[Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)

[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)

[SecretRoomsMod (by AbrarSyed)](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)

[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)

[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)

[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)

[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)

[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)

[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)

[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)

[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)

[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)

[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)

[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)

[Farmer's Compats (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/farmers-compats)

[Awesome Dungeon Ocean edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-forge)

[Hourglass (by DuckyCrayfish)](https://www.curseforge.com/minecraft/mc-mods/hourglass)

[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)

[VR Library (by Vuserr)](https://www.curseforge.com/minecraft/mc-mods/vr-library)

[Create Compats (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compats)

[Medieval Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/medieval-music)

[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)

[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)

[Awesome Dungeon - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-forge)

[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)

[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)

[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)

[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)

[Signpost (by Gollorum)](https://www.curseforge.com/minecraft/mc-mods/signpost)

[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)

[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)

[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)

[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)

[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)

[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)

[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)

[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)

[Oreberries Replanted (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted)

[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)

[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)

[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)

[Patterned Glass (by thenamesnano)](https://www.curseforge.com/minecraft/mc-mods/patterned-glass)

[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)

[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)

[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)

[Unstructured [Fabric/Forge] (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/unstructured)

[Basic Nether Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores)

[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)

[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)

[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)

[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)

[WFC Waffles For Croptopia (by thehyvis)](https://www.curseforge.com/minecraft/mc-mods/wfc-waffles-for-croptopia)

[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)

[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)

[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)

[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)

[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)

[Scaling Health (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/scaling-health)

[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)

[ConnectedTexturesMod (by tterrag1098)](https://www.curseforge.com/minecraft/mc-mods/ctm)

[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)

[Player Companions (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/player-companions)

[Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)

[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)

[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)

[Death Counter (Forge) (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/death-counter)

[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)

[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)

[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)

[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)

[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)

[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)

[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)

[Lightspeed - Launch optimizations (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)

[The Abyss II - The Other Side (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii)

[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)

[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)

[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)

[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)

[Block Limit Fix (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/block-limit-fix)

[Merchant Markers [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/merchant-markers)

[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)

[Cataclysm Weaponery (by eyezlevrai)](https://www.curseforge.com/minecraft/mc-mods/cataclysmweaponery)

[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)

[Botania: Garden of Glass (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania-garden-of-glass)

[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)

[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)

[ViesCraft Machines (by Vies)](https://www.curseforge.com/minecraft/mc-mods/viescraft-airships)

[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)

[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)

[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)

[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)

[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)

[Fantasy's Furniture (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)

[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)

[Ad Astra!: Giselle Addon (by 지젤쟝다)](https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon)

[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)

[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)

[Immersive Portals (for Forge) (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge)

[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)

[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)

[Create Ad Astra Compat (by ssm227)](https://www.curseforge.com/minecraft/mc-mods/create-ad-astra-compat)

[Why stacks of 16? (by LaidBackSloth42)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)

[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)

[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)

[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)

[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)

[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)

[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)

[Infused Foods (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/infused-foods)

[Builders Crafts & Additions (Forge) (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/buildersaddition)

[Shadowlands (by dreamcritting)](https://www.curseforge.com/minecraft/mc-mods/shadowlands)

[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)

[Star Wars Planets Ad Astra! (by TathanDev)](https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra)

[Longer Login Times (by Dremoline)](https://www.curseforge.com/minecraft/mc-mods/longer-login-times)

[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)

[Plantable Ores (by Vuserr)](https://www.curseforge.com/minecraft/mc-mods/plantable-ores)

[MC Story Mode Armors [Forge / Fabric] (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcsa)

[The Lost Castle (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/the-lost-castle)

[MCglTF (by protoxy22)](https://www.curseforge.com/minecraft/mc-mods/mcgltf)

[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)

[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)

[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)

[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)

[Brutal Bosses - Dungeon Bosses (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)

[Spoorn Armor Attributes [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoorn-armorattributes)

[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)

[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)

[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)

[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)

[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)

[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)

[Ulterlands: Worlds Apart (by Zoruk_Mods)](https://www.curseforge.com/minecraft/mc-mods/the-ulterlands)

[Better Fishing Rods (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/better-fishing-rods)

[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)

[Dragon Mounts: Legacy (by UnitKay9)](https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy)

[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)

[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)

[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)

[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)

[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)

[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)

[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)

[Spoorn Weapon Attributes [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoorn-weapon-attributes)

[One Twenty 1.20 Backport (by kleiders3010)](https://www.curseforge.com/minecraft/mc-mods/one-twenty-backport)

[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)

[Many Advancements (by ph5r0)](https://www.curseforge.com/minecraft/mc-mods/more_advancements)

[Croptopia Additions (by Numerosityy)](https://www.curseforge.com/minecraft/mc-mods/croptopia-additions)

[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)

[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)

[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)

[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)

[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)

[Move Plus (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/move-plus)

[Twilight Forest: The Lost Blocks (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/twilight-forest-the-lost-blocks)

[Infernal Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion)

[Custom Portal API [Forge] (by mysticpasta1)](https://www.curseforge.com/minecraft/mc-mods/custom-portal-api-forge)

[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)

[Epic Knights: Shields, Armor and Weapons [Fabric & Forge] (by magistu_)](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)

[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)

[Stylecolonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/stylecolonies)

[Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)

[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)

[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)

[Architect's Palette (by Jsburg)](https://www.curseforge.com/minecraft/mc-mods/architects-palette)

[Forgiving World - Dimension Stacking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/forgiving-world)

[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)

[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)

[Shield mechanics (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/shield-mechanics)

[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)

[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)

[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)

[Limited Chunkloading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)

[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)

[Basic End Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-end-ores)

[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)

[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)

[Copperized (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/copperized)

[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)

[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)

[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)

[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)

[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)

[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)

[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)

[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)

[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)

[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)

[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)

[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)

[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)

[Colored Bricks Mod (by pinary_pi)](https://www.curseforge.com/minecraft/mc-mods/colored-bricks-mod)

[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)

[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)

[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)

[Cave Spelunking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/caveore)

[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)

[MineColonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)

[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)

[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)

[Awesome Dungeon The End edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-forge)

[Decoration and Furniture (by skart2000)](https://www.curseforge.com/minecraft/mc-mods/decoration-and-furniture)

[Fish of Thieves (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves)

[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)

[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)

[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)

[Music Duration Reducer (by LudoCrypt)](https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer)

[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)

[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)

[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)

[Copper Drops (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/copper-drops)

[Prefab (by wiggles_gaming)](https://www.curseforge.com/minecraft/mc-mods/prefab)

[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)

[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)

[Modern Elevators and Escalators (by jonafanho)](https://www.curseforge.com/minecraft/mc-mods/modern-elevators-and-escalators)

[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)

[Atlantis (by mysticpasta1)](https://www.curseforge.com/minecraft/mc-mods/atlantis)

[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)

[Advancements Tracker and Overview (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/advancements-tracker)

[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)

[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)

[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)

**Comment by Mysticpasta1** [comment]
please try with atlantis and it's dependencies only

**Comment by Mysticpasta1** [comment]
removed ctov references but other than that idk why you are crashing
