### ISSUE TITLE
Texture glitch in June 29 atlantis update.

### ISSUE THREAD

**Issue by PercyJames** [Mysticpasta1/Dimension-Atlantis#82]
![2023-06-29_18 49 25](https://github.com/DimensionalDevelopment/atlantis/assets/65469481/b9ba4c0f-2bec-4660-ba7d-b027128bccb1)
![2023-06-29_18 49 39](https://github.com/DimensionalDevelopment/atlantis/assets/65469481/7c28c4dc-a5eb-42e7-be8f-f34d8d4f8a21)

**Comment by Mysticpasta1** [comment]
thank you for catching that I will fix immedately

**Comment by PercyJames** [comment]
np!

**Comment by Mysticpasta1** [comment]
will be fixed in the next update for 1.19.2 forge
