### ISSUE TITLE
'Data Pack Validation failed' error on new world creation for 2.1 onwards

### ISSUE THREAD

**Issue by Mecheon** [Mysticpasta1/Dimension-Atlantis#84]
Hello

Trying to create a new world using Atlantis versions 2.1 for 1.19.2 onwards for Forge  results in Data Pack Validation Failed error.

Seperate testing confirms issue is not present in version 1.7.4. Only mods being used are Atlantis and its dependencies (Cloth, Custom Poortal and Gecko)

Reading through the listener, appears 
'java.util.concurrent.CompletionException: java.lang.IllegalStateException: Unbound values in registry ResourceKey[minecraft:root / minecraft:worldgen/processor_list]: [ctov:farm/plains/normal, ctov:orchard/plains/normal]' 
to be the stopper on this one

Referring the specific error message, attempted to install latest 1.19.2 version of CTOV to see if an unlisted dependency. Did not fix, error still occured. Confirmed CTOV working independantly on version 3.1.3 on same setup with Atlantis mods disabled.

Editing house.json  to remove the two ctov:farm/plains/normal and replace with minecraft:empty allowed datapack to generate, and world to generate alongside, but haven't tested fully as to consequences of this

**Comment by Mysticpasta1** [comment]
will be fixed in the next update for 1.19.2 forge
