### ISSUE TITLE
no recipes or events from the mod work

### ISSUE THREAD

**Issue by StarWalker1** [Mysticpasta1/Dimension-Atlantis#86]
There are no recipes, ore generation, structure generation, and the portal does not spawn. Running a custom modpack(modlist here): https://legacy.curseforge.com/minecraft/modpacks/infinite-expanse/relations/dependencies
I have nothing relating to atlantis failing to load in startup or log files. Are there any known incompatibilities that may be breaking it?

on version 2023.7.2-1.19.2-2.5

edit: many items also seem to be missing lang references 
![image](https://github.com/DimensionalDevelopment/atlantis/assets/44377596/629cf129-25f1-4fc3-97a4-e522b1a38bc4)

**Comment by Mysticpasta1** [comment]
please try with atlantis and dependencies only

**Comment by Mysticpasta1** [comment]
recipes should be fix in the next update for 1.19.2 forge other than that idk

**Comment by Mysticpasta1** [comment]
checking events they work fine it would be another mod causing it
