### ISSUE TITLE
Bedrock layer is chipped in dimension atlantis  1.16.5 Forge

### ISSUE THREAD

**Issue by GoldenTotem** [Mysticpasta1/Dimension-Atlantis#88]
Minecraft 1.16.5  Forge 36.2.35  Mod 1.1.1

At y=0, there are not always bedrock. Because block algae occurs at there.
Not only bedrock layer, but also many algaes occur in stone layer.

**Comment by Mysticpasta1** [comment]
not maintaining 1.16.5 please update to 1.19.2 forge :D
