### ISSUE TITLE
[Fabric] Modrinth parity

### ISSUE THREAD

**Issue by ColonelGerdauf** [Mysticpasta1/Dimension-Atlantis#89]
The version on Modrinth is latest at 1.17.1
The version on CurseForge is on 1.18.2

Some version parity is appreciated, given how much easier it is for people, especially those using launchers like Prism.

**Comment by Mysticpasta1** [comment]
I abandoned the modrinth, not making enough money from it to put anymore downloads on there, I will only be uploading the curseforge for forge unless waterpicker does stuff for it

**Comment by OrdinaryCloverOC** [comment]
modrinth payout increased a lot recently (some months ago i think), my revenue increased from $3 to over $10 total for my own small projects. wondering if modrinth will be considered again?

**Comment by Mysticpasta1** [comment]
still not paying every day like my CF does
