### ISSUE TITLE
Broken textures

### ISSUE THREAD

**Issue by ghost** [Mysticpasta1/Dimension-Atlantis#92]
The portal's textures, I don't know if it's like this or if it's broken,
![2023-08-30_14 37 25](https://github.com/DimensionalDevelopment/atlantis/assets/130255931/a31387ec-fde3-4e45-aee7-4b91c34addac)
The textures of the corals are not displaying. It happens with all the corals and plants from the mod.
![2023-08-30_14 38 03](https://github.com/DimensionalDevelopment/atlantis/assets/130255931/1e8be5d3-4f14-4412-9f61-4f1f1292950d)
![2023-08-30_14 38 07](https://github.com/DimensionalDevelopment/atlantis/assets/130255931/99f6717c-f6f9-46b4-9944-0d1cd0436446)
You can break the portal blocks by hand and obtain them in survival mode.
![2023-08-30_14 43 58](https://github.com/DimensionalDevelopment/atlantis/assets/130255931/3c99c924-319f-44a0-8f55-1f922eeb4909)

I'm using the most recent version: atlantis-2023.8.30-1.19.2-3.6-forge

**Comment by Mysticpasta1** [comment]
The custom portal just does that on the gui, idk how to fix it as it is an issue with the library itself :<
the rest will be fixed next update  :D
