### ISSUE TITLE
1.20.1 : Exception generating new chunk

### ISSUE THREAD

**Issue by Daltaxy** [Mysticpasta1/Dimension-Atlantis#95]
Hello.
Before crashing due to a rendering issue, I was at my base (above water).
I restart the game and rejoin, and this time it crashes due to placed_feature / atlantis:jetstream_lake_feature_atlantis
[crash-2023-10-13_18.11.19-server.txt](https://github.com/DimensionalDevelopment/atlantis/files/12895497/crash-2023-10-13_18.11.19-server.txt)
latest.log : https://mclo.gs/lLfUV19

**Comment by Daltaxy** [comment]
crashed once but it seems fine now, weird...

**Comment by Daltaxy** [comment]
crashed again today, really seems to be random
https://mclo.gs/er7dVAB

**Comment by Mysticpasta1** [comment]
seems to be fix or unreplicatable in dev

**Comment by Daltaxy** [comment]
indeed the issue was with the mod Cyanide, causing many more issues
