### ISSUE TITLE
Red Stone Fault

### ISSUE THREAD

**Issue by Mnibr** [Mysticpasta1/Dimension-Atlantis#96]
After installing Atlantis, there was an issue with the strength of the red stone in the comparator. Originally, it was supposed to output 3 signals at 45 items (one signal per 15 items), but now it has become 3 signals at 69 items (one signal per 23 items), which has caused numerous large red stone machines to be damaged. Please fix it

**Comment by Mysticpasta1** [comment]
I need more info, how does it occur? what machine did you try it with? how do I make the machine? what version of atlantis, minecraft, mod loader, mod loader version?
