### ISSUE TITLE
1.18.1 Fabric won't load in dimension, "Caused by: java.lang.NoSuchMethodError: 'float com.mystic.atlantis.entities.renders.JellyfishEntityRenderer.handleRotationFloat(net.minecraft.class_1309, float)'"

### ISSUE THREAD

**Issue by luisism** [Mysticpasta1/Dimension-Atlantis#98]
As stated in title, game will only run the dimension for a small amount of time before crashing and showing the message "Caused by: java.lang.NoSuchMethodError: 'float com.mystic.atlantis.entities.renders.JellyfishEntityRenderer.handleRotationFloat(net.minecraft.class_1309, float)'". 
Full crash report: https://bytebin.lucko.me/14eP1RLFhv

**Comment by Mysticpasta1** [comment]
1.18.1 fabric is not supported rn, forge 1.18.2 and 1.20.1 are both supported atm
