### ISSUE TITLE
[Translation Updates]:  Some new translations for zh_cn.json of the 1.20.1-forge branch

### ISSUE THREAD

**Issue by LuminaHeinsborough** [Mysticpasta1/Dimension-Atlantis#99]
For the compatibalities with Nature’s Compass and Explorer's Compass。

"biome.atlantis.atlantean_garden": "亚特兰花园",
"biome.atlantis.atlantean_islands_biome": "亚特兰群岛",
"biome.atlantis.atlantis_biome": "亚特兰蒂斯",
"biome.atlantis.coconut_isles": "椰子群岛",
"biome.atlantis.goo_lagoons": "酷乐湖",
"biome.atlantis.jellyfish_fields": "水母田",
"biome.atlantis.volcanic_darksea": "火山暗海",
"structure.atlantis.atlantean_village": "亚特兰村庄",
"dimension.atlantis.atlantis": "亚特兰蒂斯",
"structure.atlantis.configured_atlantean_city": "亚特兰城",
"structure.atlantis.configured_atlantean_fountain": "亚特兰喷泉",
"structure.atlantis.configured_atlantean_house_1": "亚特兰房屋1",
"structure.atlantis.configured_atlantean_house_3": "亚特兰房屋3",
"structure.atlantis.configured_atlantean_spire": "亚特兰尖塔",
"structure.atlantis.configured_atlantean_temple": "亚特兰神庙",
"structure.atlantis.configured_atlantean_tower": "亚特兰塔",
"structure.atlantis.configured_oyster_structure": "牡蛎结构",

**Comment by Mysticpasta1** [comment]
"biome.atlantis.atlantean_garden": "Atlantean Garden",
  "biome.atlantis.atlantean_islands_biome": "Atlantean Islands Biome",
  "biome.atlantis.atlantis_biome": "Atlantis Biome",
  "biome.atlantis.coconut_isles": "Coconut Isles",
  "biome.atlantis.goo_lagoons": "Goo Lagoons",
  "biome.atlantis.jellyfish_fields": "Jellyfish Fields",
  "biome.atlantis.volcanic_darksea": "Volcanic Darksea",
  "structure.atlantis.atlantean_village": "Atlantean Village",
  "dimension.atlantis.atlantis": "Atlantis",
  "structure.atlantis.configured_atlantean_city": "Atlantean City",
  "structure.atlantis.configured_atlantean_fountain": "Atlantean Fountain",
  "structure.atlantis.configured_atlantean_house_1": "Atlantean House Variant 1",
  "structure.atlantis.configured_atlantean_house_3": "Atlantean House Variant 3",
  "structure.atlantis.configured_atlantean_spire": "Atlantean Spire",
  "structure.atlantis.configured_atlantean_temple": "Atlantean Temple",
  "structure.atlantis.configured_atlantean_tower": "Atlantean Tower",
  "structure.atlantis.configured_oyster_structure": "Giant Oyster",

english variations for you make sure the translations to zh_ch are correct
